azavea/osmesa

src/stats/src/main/scala/osmesa/stats/Router.scala
src/stats/src/main/scala/osmesa/stats/TileLayouts.scala

This PR cleans up some slightly ambiguous code and ensures that CORS headers are uniquely assigned to responses.

Clean up CORS header code

---

src/ingest/src/main/scala/osmesa/ingest/Constants.scala
src/ingest/src/main/scala/osmesa/ingest/ProcessOSM.scala

This PR pulls in code contributed by Seth Fitzsimmons into the Ingest project as a means to replace some Vectorpipe functions that have not scaled well to planet-scale ingests.  These functions have been confirmed to run on a subset of OSM, but not on the full planet history file.

Import DataFrame-based code for ingesting OSM

---

src/ingest/build.sbt
src/project/Version.scala
src/project/build.properties

Most important is the SBT version bump which resolved:
```scala
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: it.geosolutions.imageio-ext#imageio-ext-tiff;1.1.18: java.lang.NullPointerException at sbt.internal.librarymanagement.ivyint.GigahorseUrlHandler.getURLInfo(GigahorseUrlHandler.scala:54)
[warn] 	:: it.geosolutions.jaiext.affine#jt-affine;1.0.16: java.lang.NullPointerException at sbt.internal.librarymanagement.ivyint.GigahorseUrlHandler.getURLInfo(GigahorseUrlHandler.scala:54)
...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn] 	Note: Unresolved dependencies path:
[warn] 		it.geosolutions.jaiext.affine:jt-affine:1.0.16
[warn] 		  +- …
```

Version Bumps

---

src/ingest/src/main/scala/osmesa/ingest/Ingest.scala

Prior to this, cached stages will be run once to populate the cache (triggered by `write`) and once where they're used subsequently.
The alternative to this is to add a `cache` call to the write chain to avoid ORC read overhead, but we've seen problems with `cache` on larger stages where the job eventually fails.
This also fixes the local FS cache implementation.

Cache improvements

---

src/common/src/main/scala/osmesa/common/GenerateVT.scala
src/ingest/build.sbt

Tippeanoe's default behavior is to pre-gzip the pbf files as it does a directory-dump of vector tiles. This PR adds similar functionality and sets the appropriate headers on S3.

Add gzip compression on write to S3

---

src/ingest/src/main/scala/osmesa/ingest/Ingest.scala
src/ingest/src/main/scala/osmesa/ingest/ProcessOSM.scala

It is desirable to be able to produce vector tiles over some small subset of land without needing to produce  geographic extract according to that extent ahead of time. This PR adds the ability to provide a bounding box during `spark-submit` which filters out non-contained geometries.

Add a bounding box argument

---

src/common/src/main/scala/osmesa/common/streaming/AugmentedDiffMicroBatchReader.scala
src/common/src/main/scala/osmesa/common/streaming/AugmentedDiffSource.scala
src/common/src/main/scala/osmesa/common/streaming/ChangesMicroBatchReader.scala
src/common/src/main/scala/osmesa/common/streaming/ChangesSource.scala
src/common/src/main/scala/osmesa/common/streaming/ChangesetsMicroBatchReader.scala
src/common/src/main/scala/osmesa/common/streaming/ChangesetsSource.scala
src/common/src/main/scala/osmesa/common/streaming/ReplicationStreamMicroBatchReader.scala

Fixes various off-by-one errors resulting from varying `(.., ..]` (exclusive/inclusive) `[.., ..]` (inclusive/inclusive) ranges. Also handles sequence ranges provided as options correctly.
Fixes #75

Simplify offset handling + parallelize reads

---

src/analytics/sql/materialized_views/user_statistics.sql

In the `user_statistics` materialized view, certain users were not being displayed due to nulls which were causing no harm. A more cautious and less picky `LEFT JOIN` preferring strategy has been adopted instead to avoid unnecessary errors

Use left joins where nulls can be tolerated

---

src/analytics/src/main/scala/osmesa/analytics/Footprints.scala
src/analytics/src/main/scala/osmesa/analytics/oneoffs/Footprint.scala
src/common/src/main/scala/osmesa/common/model/impl/package.scala
src/common/src/main/scala/osmesa/common/model/package.scala
src/common/src/main/scala/osmesa/common/raster/package.scala

Namely, that it actually runs through.
When generating footprints for large numbers of users, many, many intermediate tiles are produced. Prior to SparseIntTile, each was backed by an array of rows * cols but was largely empty. Spark shuffle / spill serialization compressed the Array[Byte] representations of these backing arrays **extremely** well. However, Spark reliably OOM'd while deserializing and allocating these large backing arrays.
By switching to `Map`- and `LongMap`-backed `IntTile`s, memory usage is **dramatically** reduced (the Detroit sample went from a 2.7GB in-memory representation to 39MB) *for this use-case* (where tiles are largely empty) with the additional benefit of being able to pass the backing `Map`s directly to Spark without an intermediate deserialization step.

User footprint rendering improvements

---

src/common/src/main/scala/osmesa/common/util/DBUtils.scala

Previously, it defaulted to `null`, which prevented URLs like `postgresql:///db` from working.

Omitting host in a database URL defaults to localhost

---

src/analytics/src/main/scala/osmesa/analytics/oneoffs/AugmentedDiffStreamProcessor.scala
src/analytics/src/main/scala/osmesa/analytics/oneoffs/ChangesetStats.scala
src/analytics/src/main/scala/osmesa/analytics/updater/Implicits.scala
src/common/build.sbt
src/common/src/main/scala/osmesa/common/ProcessOSM.scala
src/common/src/main/scala/osmesa/common/functions/package.scala
src/ingest/src/main/scala/osmesa/ingest/TagChanges.scala

This fixes up some UDFs that weren't migrated to Spark JTS, changes lat/lon representation to `Double`s (to match OSM precision), silences a minor compiler warning, and fixes assembly construction (some dependency had its signature filename change from `ECLIPSEF.RSA` to `ECLIPSE_.RSA`). This also adds a new oneoff: `TagChanges`, which will produce tagging deltas between element versions.
The primary upshot of this is that `ChangesetStats` will run to completion again.

Misc fixes

---

src/common/src/main/scala/osmesa/common/ProcessOSM.scala

Due to the order of joining in `ProcessOSM.constructGeometries`, the resulting frame has a `geom` column of type `point`.  Since JTS frames only provides functions to make geometries more specific and reversing the join order is not allowed (for some reason), I've provided a local udf to do the conversion.

`constructGeometries` should produce a geom column with type `Geometry`

---

src/common/src/main/scala/osmesa/common/ProcessOSM.scala
src/common/src/main/scala/osmesa/common/model/Element.scala
src/common/src/main/scala/osmesa/common/model/impl/package.scala
src/common/src/main/scala/osmesa/common/model/package.scala

`Double`s are equivalent for our purposes and work better with `ExpressionEncoder`s (`BigDecimal`s were being converted to `null` when serialized into `Row`s as part of #106). Spark JTS geometry constructions are happy with either, so this shouldn't affect anything.

Replace BigDecimals with Doubles

---

src/common/src/main/scala/osmesa/common/ProcessOSM.scala

After much investigation, @jpolchlo (with assistance from @metasim) discovered that we were attempting to use JTS UDTs prior to their being registered. Initializing them lazily causes them to reference `GeometryUDT` after registration.

JTS Frames fixes

---

src/analytics/build.sbt
src/analytics/src/main/scala/osmesa/analytics/Footprints.scala
src/analytics/src/main/scala/osmesa/analytics/oneoffs/Footprint.scala
src/analytics/src/main/scala/osmesa/analytics/oneoffs/HashtagFootprintUpdater.scala
src/analytics/src/main/scala/osmesa/analytics/oneoffs/UserFootprintUpdater.scala
src/common/build.sbt

Previously, footprints updated from sequences could be missing data, as Scala `Stream`s were being partially consumed prior to data being processed.
This also cleans things up a bit and uses `Set`s to group sequences rather than `Seq`s.

User footprint fixes

---

src/common/src/main/scala/osmesa/common/model/AugmentedDiff.scala
src/common/src/main/scala/osmesa/common/model/Change.scala
src/common/src/main/scala/osmesa/common/model/Changeset.scala
src/common/src/main/scala/osmesa/common/sources/AugmentedDiffMicroBatchReader.scala
src/common/src/main/scala/osmesa/common/sources/AugmentedDiffReader.scala
src/common/src/main/scala/osmesa/common/sources/ChangeMicroBatchReader.scala
src/common/src/main/scala/osmesa/common/sources/ChangeReader.scala
src/common/src/main/scala/osmesa/common/sources/ChangesetMicroBatchReader.scala
src/common/src/main/scala/osmesa/common/sources/ChangesetReader.scala
src/common/src/main/scala/osmesa/common/sources/ReplicationReader.scala
src/common/src/main/scala/osmesa/common/sources/ReplicationStreamBatchReader.scala
src/common/src/main/scala/osmesa/common/sources/ReplicationStreamMicroBatchReader.scala

This will limit the ability for schemas to get out of sync with case classes used to represent data.

Remove explicit schemas

---

src/analytics/src/main/scala/osmesa/analytics/oneoffs/ChangesetStats.scala
src/analytics/src/main/scala/osmesa/analytics/oneoffs/ChangesetStreamProcessor.scala
src/analytics/src/main/scala/osmesa/analytics/oneoffs/Footprint.scala
src/analytics/src/main/scala/osmesa/analytics/oneoffs/HashtagFootprintUpdater.scala
src/analytics/src/main/scala/osmesa/analytics/oneoffs/MergedChangesetStreamProcessor.scala
src/common/src/main/scala/osmesa/common/functions/osm/package.scala
src/common/src/main/scala/osmesa/common/functions/package.scala

This makes it easier to populate an empty database with backfilled statistics.
A number of UDFs were rewritten as functions operating on `Column`s to improve performance (no need to fully deserialize when using the latter).

Modify ChangesetStats to produced normalized data

---

src/analytics/src/main/scala/osmesa/analytics/oneoffs/ChangesetStats.scala

Prior to this PR, tags on deleted elements would be `null`, preventing those elements from being categorized correctly (or at all). By applying a window function to nodes and ways before filtering, the tags present on the version immediately prior to deletion will be used.
This PR also breaks out deletes (otherwise they'd be combined with modifications).

Track deletes and distinguish from modifications

---

src/common/src/main/scala/osmesa/common/sources/AugmentedDiffSource.scala
src/common/src/main/scala/osmesa/common/sources/ChangeSource.scala
src/common/src/main/scala/osmesa/common/sources/ChangesetSource.scala

Path segments are also split up to match partitioning of OSM replication files.
Fixes #122

Fetch gzipped augmented diff JSON

---

src/analytics/src/main/scala/osmesa/analytics/oneoffs/FacetedEditHistogramTileCreator.scala

All elements must be present when preprocessing. Otherwise deletes won't pick up their last-known coordinates.

Fix delete tracking in faceted edit histogram tiles

---

src/analytics/src/main/scala/osmesa/analytics/EditHistogram.scala
src/analytics/src/main/scala/osmesa/analytics/updater/package.scala

We're vectorizing 128x128 grids, so a target grid of 128x128 makes more sense than the default 4096x4096 grid.

Reduce MVT granularity

---

src/analytics/src/main/scala/osmesa/analytics/Analytics.scala
src/common/src/main/scala/osmesa/common/ProcessOSM.scala
src/common/src/main/scala/osmesa/common/functions/package.scala
src/ingest/src/main/scala/osmesa/ingest/MakeGeometries.scala

Most notable is the additional of a `bbox` column in geometry output, which facilitates preliminary bounding box filtering before deserializing WKB and apply spatial operators.

Misc. cleanup

---

README.md

They've been moved to osmesa-stat-server, as that's what actually cares about the aggregations

Correct materialized view locations

---

README.md

These correspond to UDFs with VectorPipe, so implementation may drift over time.

Enumerate tag and metadata values used for each statistic

---

src/analytics/src/main/scala/osmesa/analytics/oneoffs/StreamingAOIMonitor.scala

The postgres table containing notifications was simplified such that we now just have a Notification table that directly contains each geometry and its name. This is because the MVP prototype specifically describes a notification as relating one to one to an AOI geom. No sense building something more complicated to prove a concept. We can always re-normalize later. Given that we want to just group on notification id. 
The data types were refactored a bit in order to match names to the types a bit better.
Deletes the remaining references/usages to the stubs that provided static geojson data.

Integrate postgres Notification list with AugmentedDiff source

---

src/analytics/src/main/scala/osmesa/analytics/oneoffs/StreamingAOIMonitor.scala

Supersedes https://github.com/azavea/osmesa/pull/160.
We expect to use this branch for development of this feature. Additional changes to this work should be PRed here.
We are developing a facility to track areas of interest and provide periodic updates to subscribed users as to edits occurring in those regions. This PR provides the component which will monitor and aggregate those changes and queue up the information that will be conveyed to the users.
We intend to deploy this service via ECS scheduled tasks at preset intervals (monthly, weekly, daily), and each interval may aggregate and report its results differently. Email notifications will be handled by a different service.

Add Streaming AOI Monitor one-off script

---

deployment/streaming/Makefile
deployment/streaming/scripts/define-production-streaming-update-tasks.sh
deployment/streaming/scripts/define-streaming-vectortile-tasks.sh
deployment/streaming/scripts/get-tag.sh

In our first migration to production, some bugs in the required scripts were encountered.  This PR fixes those scripts.

Update deployment scripts to work for production migrations

---

src/analytics/build.sbt
src/analytics/src/main/scala/osmesa/analytics/oneoffs/StreamingAOIMonitor.scala
src/project/Dependencies.scala
src/project/Version.scala

This PR uses [Apache Commons Email](http://commons.apache.org/proper/commons-email/) to send plain text emails to an unauthenticated SMTP endpoint as long as the environment variable `AOI_FROM_ADDRESS` is set and not empty. Otherwise, the CLI continues to default to publishing email messages to stdout.
I configured my environment with:
```
export AOI_FROM_ADDRESS=noreply@foo.com
export AOI_SMTP_HOSTNAME=localhost
export AOI_SMTP_PORT=1025
```
and started a [MailHog](https://github.com/mailhog/MailHog) container with:
```
docker run -p 8025:8025 -p 1025:1025 mailhog/mailhog
```
Then I ran the CLI from SBT after configuring some Notification objects in the connected Postgres database, something like:
```
./sbt
project analytics
test:runMain osmesa.analytics.oneoffs.StreamingAOIMonitor …
```

Send SMTP Emails from StreamingAOIMonitor CLI

---

src/apps/src/main/scala/osmesa/apps/streaming/AOIMonitor.scala

Fixes / cleans up a few issues in the AOIMonitor command app. See commit log for details on each fix.
The fallout of removing the unused withDelta call, along with adding a VectorPipe default spark session provider in geotrellis/vectorpipe#122 is that this command app no longer relies on anything specific to osmesa.

AOIMonitor command app miscellaneous cleanup

---

deployment/streaming/Makefile
deployment/streaming/config-deployment.mk.template
deployment/streaming/scripts/batch-generate-edit-histograms.sh
deployment/streaming/scripts/batch-generate-footprints.sh
deployment/streaming/scripts/batch-process.sh
deployment/streaming/scripts/emr-configurations/batch-process.json
src/analytics/src/main/scala/osmesa/analytics/stats/ChangesetStatsForeachWriter.scala

This should fix total_edits ending up null as
soon as one of the operands is null for any
given row write operation.
Both coalesces are required as a new changeset could have no interesting counts, same as the old summed changesets.
I updated the batch-process.sh script to use a json configuration for its spark conf. This should make it easier to adjust in the future. I also swapped to static instance types and EBS configuration since we need a particular combination of CPU/Mem/Disk resources for this job to run successfully.
There remain count discrepancies between the production and staging databases. I opened a separate epic to continue to investigate this (#186), as those incorrect values are outside the scope of this specific fix.
To verify this fix, I compared the total_edits in …

Fix total edit count reporting in ChangesetStatsForeachWriter

---

src/analytics/src/main/scala/osmesa/analytics/stats/package.scala
src/apps/src/main/scala/osmesa/apps/batch/ChangesetStatsCreator.scala
src/apps/src/main/scala/osmesa/apps/streaming/ChangesetStatsUpdater.scala
src/apps/src/main/scala/osmesa/apps/streaming/StreamingChangesetStatsUpdater.scala
src/build.sbt

For measurements, only include landuse and natural objects
that are areas.
For counts, count everything.
I switched `withDelta` to `withLinearDelta` to clarify
that it only computes deltas for linear features. An
alternative implementation would be to have the
original `withDelta` method compute both area and linear
deltas, but then its unclear in the generated column
whether the number has length or area units.
VectorPipe uses an outdated set of area keys from
github.com/osmlab/id-area-keys. Counts _should_ be more
accurate if we update to the latest area keys list. @mojodna 
💯 points for the comment noting where the area keys map
came from including version! 
Here's the current diff:
osmlab/id-area-keys@f645eca#diff-f36fb8b1baaccf032007cfcc70836c1d

Add measurements + counts for landuse and natural tags

---

deployment/sql/changesets.sql
deployment/sql/changesets_countries.sql
deployment/sql/changesets_hashtags.sql
deployment/sql/hashtags.sql

This PR modifies the PG database schema.
- Makes foreign keys explicit.
- Adds indices to support joins with foreign keys, and to support queries we have seen in production.
- Some tables may contain so few records that the PG query planner will not actually  use the indices, but at least they will be in place for future.
- Adding the constraint `changesets_users_id_fk` into `changesets` is going to cause problems: Executing this on a development db, I got an error because some user_ids are not present in the user table:
```sql
alter table changesets
add constraint changesets_users_id_fk
foreign key (user_id) references users;
```
The missing users issue should be resolved before changing the table create statement here.
Please beware because I have not done any integration testing and do …

Add foreign keys and indices to postgresql schema.

---

src/analytics/src/main/scala/osmesa/analytics/stats/package.scala
src/apps/src/main/scala/osmesa/apps/batch/ChangesetStatsCreator.scala

A bug was discovered where users had committed changes that were picked up by the streaming update, but lost after a bulk ingest.  These edits were valid, so there was understandable consternation.  
The problem is that we had a special `pointCounts` column function used only during bulk ingest that omitted a number of categories of edits from consideration if the underlying geometry was a point, including nodes tagged as buildings (which is [permissible](https://wiki.openstreetmap.org/wiki/Key:building)).  
This is a quick fix PR that seems to address the problem.  We ought to revisit this code, in case further streamlining is possible now that points/ways/relations are all being counted similarly.

Do not count point stats differently during batch ingest

---

deployment/batch/makefiles/Makefile
deployment/batch/makefiles/config-run.mk.template
deployment/batch/makefiles/scripts/latest-history-to-orc.sh
deployment/streaming/scripts/batch-process.sh

When reconstructing the staging DB, it is necessary to produce an ORC file for the planet history as well as to update a changeset ORC file. The latter was covered by a make rule, but the former task was previously left to a manual process. This PR adds automation to help with this, and combines it with the changeset ORC update. Now, from `./deployment/batch/makefile`, `make prepare-bulk-ingest` will create a cluster and add steps for both the planet history ORC conversion and the changeset ORC update. The cluster will terminate automatically after the steps terminate.
This PR replaces #200 after that PR was soiled by the commit of private information and the tree was never the same.

Facilities for bulk ingest file prep

---

deployment/streaming/Makefile
deployment/streaming/scripts/batch-process.sh
src/analytics/src/main/scala/osmesa/analytics/stats/ChangesetMetadataForeachWriter.scala
src/analytics/src/main/scala/osmesa/analytics/stats/ChangesetStatsForeachWriter.scala
src/apps/src/main/scala/osmesa/apps/batch/ChangesetMetadataCreator.scala
src/apps/src/main/scala/osmesa/apps/batch/ChangesetStatsCreator.scala

After a bulk ingest, it was noticed that there were changesets which lacked metadata.  This was particularly a problem for users whose stats weren't being accurately counted.  We observed NULL user IDs after a bulk ingest on changesets which had non-zero total edits.  Some of these mis-associations arose from an incomplete metadata source, but others were represented in the metadata ORC and were still missing in the final result.  The implication is that some records were not being correctly committed to the database.
This PR solves the DB commitment problem by wrapping our DB writes in JDBC transactions.  This allows for results to be checked for completeness and rolled back and reattempted in case of trouble.  This was by all accounts successful.
This PR does not fix the problem of …

Address NULL user_id entries

---

deployment/batch/makefiles/Makefile
deployment/batch/makefiles/config-run.mk.template
deployment/streaming/config-deployment.mk.template
src/apps/src/main/scala/osmesa/apps/batch/ChangesetMetadataCreator.scala

This PR adds some infrastructure to the batch makefiles to allow for the easy creation of a changeset metadata ORC from CSV exports from an OSM database.

Changeset metadata ORC improvements
