azavea/osmesa

src/ingest/src/main/scala/osmesa/ingest/Ingest.scala
src/ingest/src/test/scala/osmesa/OrcLatestIngestTest.scala
src/project/Version.scala

Signed-off-by: jpolchlo <jpolchlopek@azavea.com>

Update to accommodate most recent version of vectorpipe (0.2.2)

---

src/ingest/src/main/scala/osmesa/ingest/ProcessOSM.scala

Signed-off-by: jpolchlo <jpolchlopek@azavea.com>

Fix usage of posexplode to posexplode_outer

---

deployment/makefiles/Makefile
deployment/makefiles/config-aws.mk
deployment/makefiles/config-emr.mk
deployment/makefiles/config-run.mk
deployment/makefiles/scripts/configurations.json
src/ingest/src/main/scala/osmesa/ingest/Ingest.scala
src/ingest/src/main/scala/osmesa/ingest/util/Caching.scala

Provides an alternative to the current Terraform deployment scheme.  Somewhat more fiddly, but seems to work without issues.

Makefile-based AWS deployment scripts

---

src/.gitignore
src/ingest/src/main/scala/osmesa/ingest/ProcessOSM.scala
src/ingest/src/main/scala/osmesa/ingest/RegionStatsApp.scala

Tweaks to `geometriesByRegion` / `changesetsByRegion` (new) resulting from wrapping in `RegionStatsApp`.

Region stats

---

src/ingest/src/main/scala/osmesa/ingest/Ingest.scala
src/ingest/src/main/scala/osmesa/ingest/ProcessOSM.scala

Allows `Ingest` to run to completion.

Schema fixes

---

src/common/src/main/scala/osmesa/common/GenerateVT.scala
src/ingest/src/main/scala/osmesa/ingest/Ingest.scala
src/ingest/src/main/scala/osmesa/ingest/MakeTiles.scala
src/ingest/src/main/scala/osmesa/ingest/ProcessOSM.scala

This PR carries forward a workaround for a Kryo bug related to linked list serialization (it gets confused and causes a stack overflow trying to deserialize each link....)

Fix serialization error on vector tile write

---

src/ingest/src/main/scala/osmesa/ingest/ProcessOSM.scala
src/ingest/src/test/scala/osmesa/MultiPolygonRelationReconstructionSpec.scala

This should improve memory utilization slightly.

Avoid materializing entire partition iterators

---

src/ingest/src/test/scala/osmesa/ExtractMultiPolygons.scala

Fix ExtractMultiPolygons

---

src/analytics/src/main/scala/osmesa/analytics/examples/AugmentedDiffStreamProcessor.scala
src/analytics/src/main/scala/osmesa/analytics/oneoffs/AugmentedDiffStreamProcessor.scala
src/analytics/src/main/scala/osmesa/analytics/oneoffs/HashtagFootprintUpdater.scala
src/analytics/src/main/scala/osmesa/analytics/oneoffs/MergedChangesetStreamProcessor.scala
src/analytics/src/main/scala/osmesa/analytics/oneoffs/UserFootprintUpdater.scala
src/analytics/src/main/scala/osmesa/analytics/updater/package.scala
src/common/build.sbt
src/common/src/main/resources/META-INF/services/org.apache.spark.sql.sources.DataSourceRegister
src/common/src/main/scala/osmesa/common/model/AugmentedDiff.scala
src/common/src/main/scala/osmesa/common/model/package.scala
src/common/src/main/scala/osmesa/common/streaming/AugmentedDiffMicroBatchReader.scala
src/common/src/main/scala/osmesa/common/streaming/AugmentedDiffProvider.scala
src/common/src/main/scala/osmesa/common/streaming/AugmentedDiffSource.scala
src/common/src/main/scala/osmesa/common/streaming/ChangesMicroBatchReader.scala
src/common/src/main/scala/osmesa/common/streaming/ChangesSource.scala
src/common/src/main/scala/osmesa/common/streaming/ChangesetsMicroBatchReader.scala
src/common/src/main/scala/osmesa/common/streaming/ChangesetsSource.scala
src/common/src/main/scala/osmesa/common/streaming/ReplicationStreamMicroBatchReader.scala

This allows start and end sequences to be provided for augmented diff JSON.
Schemas have been moved to somewhere a bit more common.
Fixes #74

AugmentedDiffSource to replace the use of textFile

---

src/common/src/main/scala/osmesa/common/ProcessOSM.scala

When running in local mode, `Countries.all` being a `def` results in `countries.geojson` being parsed at the beginning of each task execution (and concurrently to the tune of the number of cores available). This allows parsing to occur once over the lifetime of the job.
This could use some general cleanup and also needs to be tested on a proper Spark cluster before being merged.
Refs #77

Parse countries.geojson once

---

src/.scalafmt.conf

I'm a fan of not arguing about style and leaning on tools to keep things consistent.
Thoughts?

scalafmt config

---

src/analytics/build.sbt
src/common/src/main/scala/osmesa/common/functions/package.scala

Includes a fix for the analytics assembly so it will run without signing errors.

Miscellany

---

src/analytics/src/main/scala/osmesa/analytics/Implicits.scala
src/analytics/src/main/scala/osmesa/analytics/oneoffs/FacetedEditHistogramTileCreator.scala
src/common/src/main/scala/osmesa/common/ProcessOSM.scala

* ignore facets with values of `0`
* right outer join nodes to support tracking of node edits that aren't related to any ways
* populate `nds` and `members` on deleted ways and relations

Histogram delete tracking

---

deployment/streaming/Makefile
deployment/streaming/config-aws.mk.example
deployment/streaming/docker-compose.deploy.yml.tpl
deployment/streaming/ecs-params.yml

@moradology this is ready for re-building the image + configuration to deploy the user footprint updater. Ping me on Slack for `CHANGE_START`.

User footprint updater deployment

---

src/analytics/src/main/scala/osmesa/analytics/EditHistogram.scala
src/analytics/src/main/scala/osmesa/analytics/VectorGrid.scala

Workaround for https://github.com/locationtech/geotrellis/issues/2926

Recenter updated geometries

---

src/analytics/src/main/scala/osmesa/analytics/oneoffs/StreamingAOIMonitor.scala

Print notification message for unimplemented sending in
staging/production environments.
Fixup startBeginSequence, it now properly upserts via
postgresql ON CONFLICT syntax available starting in
postgresql 9.5.
Some sample output from CLI:
```
[info] 09:16:20 AOIMonitorUtils:                                                                                                          
[info]  Running stream process from:                                                                                                      
[info]    3757399 (2019-11-04 09:14:00.0)                                                                                                 
[info]  to: …
```

Print emails to console in dev

---

src/analytics/src/main/scala/osmesa/analytics/oneoffs/StreamingAOIMonitor.scala

Allows interval to be set via env instead of CLI flag.
```
export INTERVAL=weekly
./sbt analytics/test:runMain osmesa.analytics.oneoffs.StreamingAOIMonitor --augmented-diff-source s3://bucket/path/to/aug-diffs
```
yields:
`[info] 13:47:02 AOIMonitorUtils: Processing stream for interval "Weekly" and sequence [3767750, 3777830]`
Then adding the `--interval` param back:
```
export INTERVAL=weekly
./sbt analytics/test:runMain osmesa.analytics.oneoffs.StreamingAOIMonitor --augmented-diff-source s3://bucket/path/to/aug-diffs --interval d
```
yields a "daily" run again (since cli arg overrides environment):
```
[info] 13:48:51 AOIMonitorUtils:                                                                                                         
[info]  Running stream process from: …
```

StreamingAOIMonitor INTERVAL environment variable

---

src/analytics/build.sbt
src/analytics/src/main/scala/osmesa/analytics/oneoffs/StreamingAOIMonitor.scala
src/project/Dependencies.scala
src/project/Version.scala

Restores the commit in #173 that was lost during a force push to develop yesterday.
Already been reviewed so merging immediately.

StreamingAOIMonitor: Send SMTP email if from address set

---

src/analytics/src/main/scala/osmesa/analytics/oneoffs/StreamingAOIMonitor.scala

I had a miserable time emulating RDD.groupByKey in DataFrame. I'd be very curious if you have suggestions on how to avoid dropping to RDDs for this particular aggregation now that there's a working RDD implementation to compare against.

Update StreamingAOI notification to print change + edit counts per user

---

src/analytics/src/main/scala/osmesa/analytics/oneoffs/StreamingAOIMonitor.scala

Sent to predefined admin emails set via new
config env variable AOI_ADMIN_EMAILS.
Adds a new `errorMessage` logging func to go
with `warnMessage` and updates a few logging
calls.
Note that if the whole job crashes we still won't catch it. We're handling that via some separate infrastructure changes in the backlog.
I tested this in the same way as I did for #173, with a local MailHog SMTP server running in Docker.

Rollup message send status into email message

---

src/analytics/src/main/scala/osmesa/analytics/stats/package.scala
src/apps/src/main/scala/osmesa/apps/batch/ChangesetStatsCreator.scala

Updates master for production migration.
See #204 for details.

Update master after fixing critical undercount bug

---

deployment/batch/makefiles/Makefile
deployment/batch/makefiles/config-run.mk.template
deployment/batch/makefiles/scripts/latest-history-to-orc.sh
deployment/streaming/Makefile
deployment/streaming/config-deployment.mk.template
deployment/streaming/scripts/batch-process.sh
deployment/streaming/scripts/create-log-groups.sh
deployment/streaming/scripts/define-streaming-augdiff-producer.sh
src/analytics/src/main/scala/osmesa/analytics/stats/ChangesetMetadataForeachWriter.scala
src/analytics/src/main/scala/osmesa/analytics/stats/ChangesetStatsForeachWriter.scala
src/apps/src/main/scala/osmesa/apps/batch/ChangesetMetadataCreator.scala
src/apps/src/main/scala/osmesa/apps/batch/ChangesetStatsCreator.scala

In preparation for a staging→production migration.  This PR brings in the NULL user id fixes and bulk changeset metadata creation facilities.

Merge develop into master
